Move click handler from button to the link inside the button
wikimedia/WhoWroteThat pull request #109
Opened 2019-12-05 02:41 UTC by samwilson

This might seem like an overly-large change for this little tweak,
but most of what it's doing is making the nomenclature for the
button and the link more consistent. The button is the <li> and
the link is the <a> inside it.

This patch also moves the creation of the portlet into the
getButton(), so we don't have the odd create-then-retrieve flow
in initialize(). And it turns both button and link into jQuery
objects, so we don't have to think too hard about whether they're
jQuery or HTMLElements (could have gone the other way, and done
them both as HTMLElements, but we want to use jQuery's toggle()
on them, so this is less code).

https://phabricator.wikimedia.org/T239842

Bug: T239842

2019-12-05 03:03 UTC, mooeypoo requested changes

2019-12-05 03:03 UTC, mooeypoo commented on src/Controller.js
> +		if ( $( '#' + portletId ).length === 1 && this.$button instanceof $ ) {
Why would this.$button ever be anything other than null (and then we create it) and jQuery instance? Do we need to check the existence of the portlet? Isn't it enough to just do `if ( this.$button ) return this.$button;` ?

2019-12-05 03:03 UTC, mooeypoo commented on src/Controller.js
> +		return this.getButton().find( 'a' );
If we're using this a lot, let's cache it internally. `.find( .. )` isn't entirely expensive, but it is a little bit; we could do something like

```
this.$button = $( mw.util.addPortletLink(...) );
this.$link = this.$button.find( 'a' );
```

and then `getLink()` can `return this.$link`  just so we don't have to redo the .find() again and again

2019-12-05 03:12 UTC, samwilson reviewed
Thanks, good ideas.

2019-12-05 03:12 UTC, samwilson commented on src/Controller.js
> +		if ( $( '#' + portletId ).length === 1 && this.$button instanceof $ ) {
Good point. Fixed.

2019-12-05 03:12 UTC, samwilson commented on src/Controller.js
> +		return this.getButton().find( 'a' );
Done.

2019-12-10 23:01 UTC, MusikAnimal approved these changes
Works great!

I think something like "wrapper" or "container" might be a better name than "button", but this can be addressed in another PR (or ignored, doesn't matter :).

2019-12-10 23:02 UTC, merged

2019-12-13 03:07 UTC, samwilson commented
> I think something like "wrapper" or "container" might be a better name than "button", but this can be addressed in another PR (or ignored, doesn't matter :).

Yes, I actually changed it to `portletItem` and then back again, because I didn't want the diff to be too big. I might go back and do it though.