UX improvements for Infobar
wikimedia/WhoWroteThat pull request #118
Opened 2019-12-12 22:21 UTC by MusikAnimal

Bug: T234710

2019-12-12 22:38 UTC, MusikAnimal commented
@prtksxna Would you mind looking over this too? The only thing I had problem with was the _Move username closer to 'Who Wrote That?'_ part. It's using flexbox so I sort of eye-balled it. I do think it looks better:

Before:
![Screenshot from 2019-12-12 17-35-22](https://user-images.githubusercontent.com/366374/70754702-e4ddbb00-1d05-11ea-91a3-2601e14d72dc.png)
![Screenshot from 2019-12-12 17-35-33](https://user-images.githubusercontent.com/366374/70754706-e7d8ab80-1d05-11ea-9d04-d278ce818c86.png)

After:
![Screenshot from 2019-12-12 17-20-13](https://user-images.githubusercontent.com/366374/70754039-2f5e3800-1d04-11ea-82f9-7d9c85dfb853.png)
![Screenshot from 2019-12-12 17-20-37](https://user-images.githubusercontent.com/366374/70754078-469d2580-1d04-11ea-8b86-e5a633ab81fb.png)

I tried playing with the `flex-grow` properties but couldn't come up with ratios that shifted the username further to the left, or reliably kept it at a certain placement. Would we prefer to use more finite widths, and do away with flexbox? Dare I say `table-cell`? :nauseated_face:

2019-12-12 22:52 UTC, mooeypoo commented
There are ways to set strict sizing for flex box too, and combine it with margins. I would stay away from table cell styling in css though. That is, indeed, 🤢

2019-12-13 04:49 UTC, samwilson commented
I think it's because not all siblings are flex items.

2019-12-17 23:02 UTC, mooeypoo commented
Now that we've hidden the username, we only have 2 active sections in that bar; the "Who Wrote That" logo/name and the help info with the [x]

Is this PR still relevant as a fix given the removal of the username?

2019-12-17 23:08 UTC, mooeypoo commented on src/InfoBarWidget.js
> +	this.userInfoUsernameLabel = new OO.ui.LabelWidget( {
This might not be relevant again now that the username is not in the bar

2019-12-17 23:09 UTC, mooeypoo commented on src/less/InfoBarWidget.less
> +		.wwt-infoBarWidget-username {
Same here; no longer used, no?

2019-12-17 23:09 UTC, mooeypoo requested changes
Wrote 2 places that use the username (that isn't showing anymore) to get rid of / fix. Other than that, looks good. Might also solve the UX questions :)

2019-12-18 00:37 UTC, merged

2019-12-28 05:23 UTC, prtksxna commented
> @prtksxna Would you mind looking over this too? The only thing I had problem with was the _Move username closer to 'Who Wrote That?'_ part. It's using flexbox so I sort of eye-balled it. I do think it looks better:

Thanks for tagging me and sorry for such a late reply 😓

> After:
> ![Screenshot from 2019-12-12 17-20-13](https://user-images.githubusercontent.com/366374/70754039-2f5e3800-1d04-11ea-82f9-7d9c85dfb853.png)
> ![Screenshot from 2019-12-12 17-20-37](https://user-images.githubusercontent.com/366374/70754078-469d2580-1d04-11ea-8b86-e5a633ab81fb.png)


> I tried playing with the `flex-grow` properties but couldn't come up with ratios that shifted the username further to the left, or reliably kept it at a certain placement. Would we prefer to use more finite widths, and do away with flexbox? Dare I say `table-cell`? 🤢