WelcomePopup: Fix positioning problem for long pages
wikimedia/WhoWroteThat pull request #40
Opened 2019-08-29 05:26 UTC by mooeypoo

When we have long pages where the "tools" menu is under the viewport,
the <html> tag, unhelpfully, stops (its height is limited) at the
edge of the viewport. This means that the <body> is similarly limited
in height, even though the content itself keeps going.

As a result, the popup, when instantiated, cannot be placed below
that point, which creates a popup that appears above where it should.

This is a hacky way to fix this. When and if the popup is active,
the code adds a class to the `html` block and sets it at a large
min-height that will cover at least the side menu to be able to
get the popup to appear properly.

HTML sucks.

2019-08-29 19:16 UTC, MusikAnimal commented
I'm getting `Error handling response: TypeError: Cannot read property 'WelcomeTourSeen' of undefined` on master, so I can't test this.

That aside, I wonder if it makes more sense for Who Wrote That link to be under `#p-cactions` (the "More" menu). If the viewport is that tall such that you can't see the Tools menu on page load, would they even see the welcome popup?

2019-08-29 21:10 UTC, mooeypoo commented
> I'm getting `Error handling response: TypeError: Cannot read property 'WelcomeTourSeen' of undefined` on master, so I can't test this.

eeeek. Is this in Firefox or Chrome or both? I think I know what's happening but I might need to see how to duplicate and we need to fix this either way.

> That aside, I wonder if it makes more sense for Who Wrote That link to be under `#p-cactions` (the "More" menu). If the viewport is that tall such that you can't see the Tools menu on page load, would they even see the welcome popup?

Interesting question. We should ask Ilana.

2019-08-29 22:01 UTC, MusikAnimal reviewed
I can reproduce the issue now and can confirm `min-height: 100em` fixes it. Why 100em, though? Is there a scenario where this would be too much or too little?

> > I'm getting `Error handling response: TypeError: Cannot read property 'WelcomeTourSeen' of undefined` on master, so I can't test this.
> 
> eeeek. Is this in Firefox or Chrome or both? I think I know what's happening but I might need to see how to duplicate and we need to fix this either way.

Chromium. It was quite bad because the WWT wouldn't load at all. I'll try to figure out how to reproduce it and create a ticket.

> > That aside, I wonder if it makes more sense for Who Wrote That link to be under `#p-cactions` (the "More" menu). If the viewport is that tall such that you can't see the Tools menu on page load, would they even see the welcome popup?
> 
> Interesting question. We should ask Ilana.

Yeah, now that I got the WelcomePopup working (and with this fix), I can confirm that I don't see it at all unless I scroll down. I think everyone would eventually find it, and it is sort of a "Tool" (hence belongs in that list of links), but p-cactions is a common placement for things like this too.

2019-08-30 01:37 UTC, mooeypoo commented
> I can reproduce the issue now and can confirm `min-height: 100em` fixes it. Why 100em, though? Is there a scenario where this would be too much or too little?

There probably is, but from my tests, it seemed like a safe enough space without being obtrusive if the page is too short.

> > > I'm getting `Error handling response: TypeError: Cannot read property 'WelcomeTourSeen' of undefined` on master, so I can't test this.
> > 
> > 
> > eeeek. Is this in Firefox or Chrome or both? I think I know what's happening but I might need to see how to duplicate and we need to fix this either way.
> 
> Chromium. It was quite bad because the WWT wouldn't load at all. I'll try to figure out how to reproduce it and create a ticket.
Yeah let's deal with this in a separate ticket/PR.

> > > That aside, I wonder if it makes more sense for Who Wrote That link to be under `#p-cactions` (the "More" menu). If the viewport is that tall such that you can't see the Tools menu on page load, would they even see the welcome popup?
> > 
> > 
> > Interesting question. We should ask Ilana.
> 
> Yeah, now that I got the WelcomePopup working (and with this fix), I can confirm that I don't see it at all unless I scroll down. I think everyone would eventually find it, and it is sort of a "Tool" (hence belongs in that list of links), but p-cactions is a common placement for things like this too.

I raised this to Ilana and she's created a ticket. For the moment, we can continue as if it's still going to stay in the same place, and if we change it later we can get rid of this hack.

2019-08-30 05:15 UTC, samwilson reviewed
This puts the popup in the right place, but makes it shrink and get a scroll bar!

![scrollypopup](https://user-images.githubusercontent.com/213655/63994718-3338c680-cb28-11e9-85f2-1e7873f75f81.png)

It's definitely an improvement though.

2019-08-30 05:32 UTC, mooeypoo commented
Yes, that's a "feature" of ClippableElement.

I had a whole comment about how I can't turn Clippable off, and then I realized I can, although it's a pretty yucky hack. But it does work, and honestly, the fact it's a hack is not our fault -- this should be doable upstream.

See latest change.

2019-09-03 17:56 UTC, MusikAnimal requested changes
Working great now! And I love the `height: unset` trick. I wouldn't even call that a "hack".

Just one minor comment about spacing, otherwise looks good to me.

2019-09-03 17:56 UTC, MusikAnimal commented on .jsdoc.json
> +		"OO.ui.PopupWidget": "https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.PopupWidget"
extraneous tab?

2019-09-03 23:55 UTC, mooeypoo commented on .jsdoc.json
> +		"OO.ui.PopupWidget": "https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.PopupWidget"
Oops

2019-09-04 01:04 UTC, MusikAnimal approved these changes

2019-09-04 01:05 UTC, merged