Remove 'under construction' from readme and add badges
wikimedia/WhoWroteThat pull request #73
Opened 2019-10-15 03:44 UTC by samwilson

2019-10-15 16:07 UTC, MusikAnimal requested changes
Requested one tiny change

2019-10-15 16:07 UTC, MusikAnimal commented on README.md
> +Powered by [WikiWho](https://www.wikiwho.net/).
Should be https://f-squared.org/wikiwho/ per their request

2019-10-16 01:40 UTC, samwilson commented on README.md
> +Powered by [WikiWho](https://www.wikiwho.net/).
Done.

2019-10-27 00:05 UTC, mooeypoo approved these changes

2019-10-27 00:16 UTC, merged